version: "3.8"

services:
  db:
    image: postgres:14.19-trixie
    container_name: cheburnet_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cheburnet_server_dev
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: cheburnet_server
    depends_on:
      - db
    environment:
      MIX_ENV: prod
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_DB: cheburnet_server_dev
      DATABASE_URL: ecto://postgres:postgres@db/cheburnet_server_dev
      SECRET_KEY_BASE: "CHANGE_ME"
      PHX_SERVER: "true"
    ports:
      - "4000:4000"
    command: ["mix", "phx.server"]
    restart: always

volumes:
  db_data:
